# Unit 3 Assessment

In this assignment, we will focus on healthcare. This data set is made available by MIT. It contains data about 9,026 heartbeat measurements. Each row represents a single measurement (captured on a timeline). There are a total of 80 data points (columns). This is a multiclass classification task: predict whether the measurement represents a normal heartbeat or other anomalies. 

## Description of Variables

You will use the **hearbeat_cleaned.csv** data set for this assignment. Each row represents a single measurement. Columns labeled as T1 from T80 are the time steps on the timeline (there are 80 time steps, each time step has only one measurement). 

The last column is the target variable. It shows the label (category) of the measurement as follows:<br>
0 = Normal<br>
1 = Supraventricular premature beat<br>
2 = Premature ventricular contraction<br>
3 = Fusion of ventricular and normal beat<br>
4 = Unclassifiable beat

## Goal

Use the data set **hearbeat_cleaned.csv** to predict the column called **Target**. The input variables are columns labeled as **T1 to T80**. 

## Submission:

Please save and submit this Jupyter notebook file. The correctness of the code matters for your grade. **Readability and organization of your code is also important.** You may lose points for submitting unreadable/undecipherable code. Therefore, use markdown cells to create sections, and use comments where necessary.


# Read and Prepare the Data (1 points)

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd

In [2]:
hbeat = pd.read_csv("heartbeat_cleaned.csv")

In [3]:
hbeat.shape

(7960, 81)

In [4]:
hbeat.head()

,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,...,T72,T73,T74,T75,T76,T77,T78,T79,T80,Target
0,0.987,0.892,0.461,0.1130,0.1490,0.1900,0.1650,0.1620,0.1470,0.1380,...,0.1970,0.1970,0.1960,0.2030,0.201,0.1990,0.2010,0.205,0.2080,0
1,1.000,0.918,0.621,0.1330,0.1050,0.1250,0.1170,0.0898,0.0703,0.0781,...,0.1950,0.1910,0.1520,0.1720,0.207,0.2110,0.2070,0.207,0.1720,0
2,1.000,0.751,0.143,0.1040,0.0961,0.0519,0.0442,0.0416,0.0364,0.0857,...,0.2260,0.2420,0.2440,0.2860,0.468,0.8160,0.9770,0.452,0.0519,0
3,1.000,0.740,0.235,0.0464,0.0722,0.0567,0.0103,0.0155,0.0284,0.0155,...,0.0851,0.0747,0.0515,0.0593,0.067,0.0361,0.1210,0.451,0.8690,0
4,1.000,0.833,0.309,0.0191,0.1010,0.1200,0.1040,0.0874,0.0765,0.0765,...,0.2050,0.4210,0.8030,0.9510,0.467,0.0000,0.0519,0.082,0.0628,0


In [5]:
y = hbeat['Target']
x = hbeat.drop('Target', axis=1)

In [6]:
y.unique()

array([0, 1, 2, 3, 4], dtype=int64)

In [7]:
from sklearn.model_selection import train_test_split

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.3)

In [8]:
#Target variables need to be an array with integer type
train_y = np.array(train_y)
test_y = np.array(test_y)

# Set the target values are set to be integers
train_y = train_y.astype(np.int32)
test_y = test_y.astype(np.int32)



In [9]:
train_y[0:30]

array([0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 4, 0, 4, 4, 0, 0, 0, 0, 0, 2, 0, 0,
       2, 0, 4, 2, 0, 0, 4, 2])

In [10]:
#Convert input variables to a 2-D array with float data type
train_x= np.array(train_x)
test_x= np.array(test_x)

train_x = train_x.astype(np.float32)
test_x = test_x.astype(np.float32)

In [11]:
train_x.shape

(5572, 80)

In [12]:
train_x

array([[1.    , 0.875 , 0.22  , ..., 0.327 , 0.329 , 0.324 ],
       [0.997 , 0.943 , 0.413 , ..., 0.306 , 0.297 , 0.304 ],
       [0.835 , 0.615 , 0.396 , ..., 0.282 , 0.311 , 0.286 ],
       ...,
       [1.    , 0.833 , 0.3   , ..., 0.851 , 0.426 , 0.0235],
       [0.954 , 0.971 , 0.464 , ..., 0.151 , 0.167 , 0.192 ],
       [0.825 , 0.447 , 0.45  , ..., 0.314 , 0.325 , 0.314 ]],
      dtype=float32)

In [13]:
train_x = np.reshape(train_x, (train_x.shape[0], train_x.shape[1], 1))
test_x = np.reshape(test_x, (test_x.shape[0], test_x.shape[1], 1))

In [14]:
train_x.shape, train_y.shape

((5572, 80, 1), (5572,))

In [15]:
train_x

array([[[1.    ],
        [0.875 ],
        [0.22  ],
        ...,
        [0.327 ],
        [0.329 ],
        [0.324 ]],

       [[0.997 ],
        [0.943 ],
        [0.413 ],
        ...,
        [0.306 ],
        [0.297 ],
        [0.304 ]],

       [[0.835 ],
        [0.615 ],
        [0.396 ],
        ...,
        [0.282 ],
        [0.311 ],
        [0.286 ]],

       ...,

       [[1.    ],
        [0.833 ],
        [0.3   ],
        ...,
        [0.851 ],
        [0.426 ],
        [0.0235]],

       [[0.954 ],
        [0.971 ],
        [0.464 ],
        ...,
        [0.151 ],
        [0.167 ],
        [0.192 ]],

       [[0.825 ],
        [0.447 ],
        [0.45  ],
        ...,
        [0.314 ],
        [0.325 ],
        [0.314 ]]], dtype=float32)

# Find the baseline (0.5 point)

In [16]:
from sklearn.dummy import DummyClassifier

dummy_clf = DummyClassifier(strategy="most_frequent")

dummy_clf.fit(train_x, train_y)

DummyClassifier(strategy='most_frequent')

In [17]:
from sklearn.metrics import accuracy_score
dummy_train_pred = dummy_clf.predict(train_x)

baseline_train_acc = accuracy_score(train_y, dummy_train_pred)

print('Baseline Train Accuracy: {}' .format(baseline_train_acc))

Baseline Train Accuracy: 0.5838119167264896


In [18]:
dummy_test_pred = dummy_clf.predict(test_x)

baseline_test_acc = accuracy_score(test_y, dummy_test_pred)

print('Baseline Test Accuracy: {}' .format(baseline_test_acc))

Baseline Test Accuracy: 0.5778894472361809


# Build a cross-sectional (i.e., a regular) Neural Network model using Keras (with only one hidden layer) (2 points)

In [24]:
model = keras.models.Sequential([

    keras.layers.Flatten(input_shape=[80, 1]),
    keras.layers.Dense(80, activation='relu'),
    keras.layers.Dense(5, activation='softmax')      
])

In [25]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = tf.keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=30, validation_data=(test_x, test_y))

Epoch 1/30
175/175 [==============================] - 1s 2ms/step - loss: 0.6728 - accuracy: 0.7789 - val_loss: 0.5849 - val_accuracy: 0.8162
Epoch 2/30
175/175 [==============================] - 0s 1ms/step - loss: 0.4329 - accuracy: 0.8591 - val_loss: 0.5226 - val_accuracy: 0.8057
Epoch 3/30
175/175 [==============================] - 0s 2ms/step - loss: 0.3679 - accuracy: 0.8851 - val_loss: 0.3511 - val_accuracy: 0.9037
Epoch 4/30
175/175 [==============================] - 0s 1ms/step - loss: 0.3218 - accuracy: 0.9079 - val_loss: 0.4036 - val_accuracy: 0.8911
Epoch 5/30
175/175 [==============================] - 0s 1ms/step - loss: 0.3069 - accuracy: 0.9092 - val_loss: 0.4451 - val_accuracy: 0.8325
Epoch 6/30
175/175 [==============================] - 0s 1ms/step - loss: 0.2944 - accuracy: 0.9099 - val_loss: 0.3054 - val_accuracy: 0.9200
Epoch 7/30
175/175 [==============================] - 0s 1ms/step - loss: 0.2797 - accuracy: 0.9151 - val_loss: 0.3512 - val_accuracy: 0.8936
Epoch 

In [26]:
scores = model.evaluate(test_x, test_y, verbose=0)
print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

# Huge improvement over the baseline

loss: 0.27
accuracy: 92.71%


# Build a deep cross-sectional (i.e., regular) Neural Network model using Keras (with two or more hidden layers) (2 points)

In [27]:
model = keras.models.Sequential([

    keras.layers.Flatten(input_shape=[80, 1]),
    keras.layers.Dense(60, activation='relu'),
    keras.layers.Dense(40, activation='relu'),
    keras.layers.Dense(20, activation='relu'),
    keras.layers.Dense(5, activation='softmax')      
])

In [28]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = tf.keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=30, validation_data=(test_x, test_y))

Epoch 1/30
175/175 [==============================] - 2s 3ms/step - loss: 0.6093 - accuracy: 0.7938 - val_loss: 0.5286 - val_accuracy: 0.8476
Epoch 2/30
175/175 [==============================] - 0s 2ms/step - loss: 0.4117 - accuracy: 0.8638 - val_loss: 0.5531 - val_accuracy: 0.8011
Epoch 3/30
175/175 [==============================] - 0s 2ms/step - loss: 0.3499 - accuracy: 0.8909 - val_loss: 0.3508 - val_accuracy: 0.8974
Epoch 4/30
175/175 [==============================] - 0s 2ms/step - loss: 0.3075 - accuracy: 0.9063 - val_loss: 0.7360 - val_accuracy: 0.7965
Epoch 5/30
175/175 [==============================] - 0s 2ms/step - loss: 0.3591 - accuracy: 0.8878 - val_loss: 0.5129 - val_accuracy: 0.8275
Epoch 6/30
175/175 [==============================] - 0s 2ms/step - loss: 0.3439 - accuracy: 0.8896 - val_loss: 0.3002 - val_accuracy: 0.9125
Epoch 7/30
175/175 [==============================] - 0s 2ms/step - loss: 0.2816 - accuracy: 0.9083 - val_loss: 0.3659 - val_accuracy: 0.8798
Epoch 

In [29]:
scores = model.evaluate(test_x, test_y, verbose=0)
print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 0.24
accuracy: 93.89%


# Build a LSTM Model (with only one layer) (2 points)

In [33]:
from tensorflow.keras.callbacks import EarlyStopping
earlystop = EarlyStopping(monitor='val_loss', patience=5, verbose=1, mode='auto')
callback = [earlystop]

In [34]:
n_steps = 80
n_inputs = 1

model = keras.models.Sequential([
    
    keras.layers.LSTM(40, input_shape=[n_steps, n_inputs]),
    keras.layers.Dense(5, activation='softmax')
])

In [36]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=20, validation_data = (test_x, test_y), callbacks=callback)

Epoch 1/20
175/175 [==============================] - 6s 23ms/step - loss: 1.1174 - accuracy: 0.5791 - val_loss: 1.0818 - val_accuracy: 0.5779
Epoch 2/20
175/175 [==============================] - 4s 22ms/step - loss: 1.0553 - accuracy: 0.5888 - val_loss: 1.0325 - val_accuracy: 0.6273
Epoch 3/20
175/175 [==============================] - 4s 22ms/step - loss: 1.0098 - accuracy: 0.6028 - val_loss: 1.0171 - val_accuracy: 0.5976
Epoch 4/20
175/175 [==============================] - 4s 22ms/step - loss: 0.8752 - accuracy: 0.6606 - val_loss: 0.7598 - val_accuracy: 0.7282
Epoch 5/20
175/175 [==============================] - 4s 21ms/step - loss: 0.7846 - accuracy: 0.7215 - val_loss: 0.7817 - val_accuracy: 0.7425
Epoch 6/20
175/175 [==============================] - 4s 22ms/step - loss: 0.7082 - accuracy: 0.7699 - val_loss: 0.8240 - val_accuracy: 0.7064
Epoch 7/20
175/175 [==============================] - 4s 22ms/step - loss: 0.5503 - accuracy: 0.8270 - val_loss: 0.5291 - val_accuracy: 0.8371

In [37]:
scores = model.evaluate(test_x, test_y, verbose=0)
print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 0.35
accuracy: 89.36%


# Build a deep LSTM Model (with only two layers) (2 points)

In [38]:
n_steps = 80
n_inputs = 1

model = keras.models.Sequential([
    keras.layers.LSTM(60, return_sequences=True, input_shape=[n_steps, n_inputs]),
    keras.layers.LSTM(40, return_sequences=True),
    keras.layers.LSTM(20),
    keras.layers.Dense(5, activation='softmax')
])

In [39]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=20, validation_data = (test_x, test_y), callbacks=callback)

Epoch 1/20
175/175 [==============================] - 18s 74ms/step - loss: 1.1411 - accuracy: 0.5797 - val_loss: 1.1419 - val_accuracy: 0.5779
Epoch 2/20
175/175 [==============================] - 12s 68ms/step - loss: 1.1250 - accuracy: 0.5838 - val_loss: 1.1516 - val_accuracy: 0.5779
Epoch 3/20
175/175 [==============================] - 12s 68ms/step - loss: 1.1267 - accuracy: 0.5838 - val_loss: 1.1510 - val_accuracy: 0.5779
Epoch 4/20
175/175 [==============================] - 12s 68ms/step - loss: 1.1246 - accuracy: 0.5838 - val_loss: 1.1521 - val_accuracy: 0.5779
Epoch 5/20
175/175 [==============================] - 12s 67ms/step - loss: 1.1235 - accuracy: 0.5838 - val_loss: 1.1417 - val_accuracy: 0.5779
Epoch 6/20
175/175 [==============================] - 12s 69ms/step - loss: 1.1228 - accuracy: 0.5838 - val_loss: 1.1466 - val_accuracy: 0.5779
Epoch 7/20
175/175 [==============================] - 12s 69ms/step - loss: 1.1242 - accuracy: 0.5838 - val_loss: 1.1383 - val_accuracy:

In [40]:
scores = model.evaluate(test_x, test_y, verbose=0)
print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 1.14
accuracy: 57.79%


# Build a GRU Model (with only one layer) (2 points)

In [41]:
n_steps = 80
n_inputs = 1

model = keras.models.Sequential([
    keras.layers.GRU(40, input_shape=[n_steps, n_inputs]),
    keras.layers.Dense(5, activation='softmax')
])

In [42]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=20, validation_data = (test_x, test_y), callbacks=callback)

Epoch 1/20
175/175 [==============================] - 6s 24ms/step - loss: 1.0923 - accuracy: 0.5940 - val_loss: 1.0355 - val_accuracy: 0.5955
Epoch 2/20
175/175 [==============================] - 4s 22ms/step - loss: 0.7813 - accuracy: 0.7181 - val_loss: 0.5258 - val_accuracy: 0.8095
Epoch 3/20
175/175 [==============================] - 4s 21ms/step - loss: 0.4916 - accuracy: 0.8403 - val_loss: 0.4631 - val_accuracy: 0.8472
Epoch 4/20
175/175 [==============================] - 4s 21ms/step - loss: 0.4080 - accuracy: 0.8699 - val_loss: 0.3699 - val_accuracy: 0.8911
Epoch 5/20
175/175 [==============================] - 4s 22ms/step - loss: 0.3644 - accuracy: 0.8911 - val_loss: 0.4145 - val_accuracy: 0.8727
Epoch 6/20
175/175 [==============================] - 4s 21ms/step - loss: 0.3588 - accuracy: 0.8887 - val_loss: 0.3115 - val_accuracy: 0.9116
Epoch 7/20
175/175 [==============================] - 4s 21ms/step - loss: 0.3188 - accuracy: 0.9033 - val_loss: 0.3253 - val_accuracy: 0.8982

In [43]:
scores = model.evaluate(test_x, test_y, verbose=0)
print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 0.29
accuracy: 91.21%


# Build a deep GRU Model (with only two layers) (2 points)

In [44]:
n_steps = 80
n_inputs = 1

model = keras.models.Sequential([
    keras.layers.GRU(60, return_sequences=True, input_shape=[n_steps, n_inputs]),
    keras.layers.GRU(40, return_sequences=True),
    keras.layers.GRU(20),
    keras.layers.Dense(5, activation='softmax')
])

In [45]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=20, validation_data = (test_x, test_y), callbacks=callback)

Epoch 1/20
175/175 [==============================] - 18s 74ms/step - loss: 0.9711 - accuracy: 0.6427 - val_loss: 0.6789 - val_accuracy: 0.7647
Epoch 2/20
175/175 [==============================] - 12s 71ms/step - loss: 0.5452 - accuracy: 0.8137 - val_loss: 0.4787 - val_accuracy: 0.8346
Epoch 3/20
175/175 [==============================] - 12s 71ms/step - loss: 0.4293 - accuracy: 0.8519 - val_loss: 0.4702 - val_accuracy: 0.8358
Epoch 4/20
175/175 [==============================] - 12s 69ms/step - loss: 0.3809 - accuracy: 0.8740 - val_loss: 0.5165 - val_accuracy: 0.8174
Epoch 5/20
175/175 [==============================] - 12s 67ms/step - loss: 0.3529 - accuracy: 0.8871 - val_loss: 0.4063 - val_accuracy: 0.8673
Epoch 6/20
175/175 [==============================] - 12s 67ms/step - loss: 0.3459 - accuracy: 0.8805 - val_loss: 0.3664 - val_accuracy: 0.8811
Epoch 7/20
175/175 [==============================] - 12s 68ms/step - loss: 0.3367 - accuracy: 0.8889 - val_loss: 0.3219 - val_accuracy:

In [46]:
scores = model.evaluate(test_x, test_y, verbose=0)
print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 0.29
accuracy: 92.29%


# Discussion

## List the test values of each model you built (0.5 points)

## Which model performs the best and why? (0.5 points) 

## How does it compare to baseline? (0.5 points)