# Unit 3 Assessment

In this assignment, we will focus on healthcare. This data set is made available by MIT. It contains data about 9,026 heartbeat measurements. Each row represents a single measurement (captured on a timeline). There are a total of 80 data points (columns). This is a multiclass classification task: predict whether the measurement represents a normal heartbeat or other anomalies. 

## Description of Variables

You will use the **hearbeat_cleaned.csv** data set for this assignment. Each row represents a single measurement. Columns labeled as T1 from T80 are the time steps on the timeline (there are 80 time steps, each time step has only one measurement). 

The last column is the target variable. It shows the label (category) of the measurement as follows:<br>
0 = Normal<br>
1 = Supraventricular premature beat<br>
2 = Premature ventricular contraction<br>
3 = Fusion of ventricular and normal beat<br>
4 = Unclassifiable beat

## Goal

Use the data set **hearbeat_cleaned.csv** to predict the column called **Target**. The input variables are columns labeled as **T1 to T80**. 

## Submission:

Please save and submit this Jupyter notebook file. The correctness of the code matters for your grade. **Readability and organization of your code is also important.** You may lose points for submitting unreadable/undecipherable code. Therefore, use markdown cells to create sections, and use comments where necessary.


# Read and Prepare the Data (1 points)

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd

In [2]:
hbeat = pd.read_csv("heartbeat_cleaned.csv")

In [3]:
hbeat.shape

(7960, 81)

In [4]:
hbeat.head()

T1     T2     T3      T4      T5      T6      T7      T8      T9  \
0  0.987  0.892  0.461  0.1130  0.1490  0.1900  0.1650  0.1620  0.1470   
1  1.000  0.918  0.621  0.1330  0.1050  0.1250  0.1170  0.0898  0.0703   
2  1.000  0.751  0.143  0.1040  0.0961  0.0519  0.0442  0.0416  0.0364   
3  1.000  0.740  0.235  0.0464  0.0722  0.0567  0.0103  0.0155  0.0284   
4  1.000  0.833  0.309  0.0191  0.1010  0.1200  0.1040  0.0874  0.0765   

      T10  ...     T72     T73     T74     T75    T76     T77     T78    T79  \
0  0.1380  ...  0.1970  0.1970  0.1960  0.2030  0.201  0.1990  0.2010  0.205   
1  0.0781  ...  0.1950  0.1910  0.1520  0.1720  0.207  0.2110  0.2070  0.207   
2  0.0857  ...  0.2260  0.2420  0.2440  0.2860  0.468  0.8160  0.9770  0.452   
3  0.0155  ...  0.0851  0.0747  0.0515  0.0593  0.067  0.0361  0.1210  0.451   
4  0.0765  ...  0.2050  0.4210  0.8030  0.9510  0.467  0.0000  0.0519  0.082   

      T80  Target  
0  0.2080       0  
1  0.1720       0  
2  0.0519       0  
3  0.8690       0  
4  0.0628       0  

[5 rows x 81 columns]

In [5]:
y = hbeat['Target']
x = hbeat.drop('Target', axis=1)

In [6]:
y.unique()

array([0, 1, 2, 3, 4], dtype=int64)

In [7]:
from sklearn.model_selection import train_test_split

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.3)

In [8]:
#Target variables need to be an array with integer type
train_y = np.array(train_y)
test_y = np.array(test_y)

# Set the target values are set to be integers
train_y = train_y.astype(np.int32)
test_y = test_y.astype(np.int32)



In [9]:
train_y[0:30]

array([1, 1, 0, 0, 0, 1, 4, 4, 0, 0, 4, 4, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0,
       4, 2, 4, 4, 0, 0, 0, 0])

In [10]:
#Convert input variables to a 2-D array with float data type
train_x= np.array(train_x)
test_x= np.array(test_x)

train_x = train_x.astype(np.float32)
test_x = test_x.astype(np.float32)

In [11]:
train_x.shape

(5572, 80)

In [12]:
train_x

array([[0.865 , 0.722 , 0.173 , ..., 0.308 , 0.323 , 0.312 ],
       [1.    , 0.824 , 0.188 , ..., 0.308 , 0.308 , 0.312 ],
       [1.    , 0.832 , 0.166 , ..., 0.275 , 0.281 , 0.267 ],
       ...,
       [0.    , 0.123 , 0.197 , ..., 1.    , 0.964 , 0.769 ],
       [1.    , 0.918 , 0.625 , ..., 0.0546, 0.102 , 0.181 ],
       [0.952 , 0.914 , 0.808 , ..., 0.237 , 0.237 , 0.245 ]],
      dtype=float32)

In [13]:
train_x = np.reshape(train_x, (train_x.shape[0], train_x.shape[1], 1))
test_x = np.reshape(test_x, (test_x.shape[0], test_x.shape[1], 1))

In [14]:
train_x.shape, train_y.shape

((5572, 80, 1), (5572,))

In [15]:
train_x

array([[[0.865 ],
        [0.722 ],
        [0.173 ],
        ...,
        [0.308 ],
        [0.323 ],
        [0.312 ]],

       [[1.    ],
        [0.824 ],
        [0.188 ],
        ...,
        [0.308 ],
        [0.308 ],
        [0.312 ]],

       [[1.    ],
        [0.832 ],
        [0.166 ],
        ...,
        [0.275 ],
        [0.281 ],
        [0.267 ]],

       ...,

       [[0.    ],
        [0.123 ],
        [0.197 ],
        ...,
        [1.    ],
        [0.964 ],
        [0.769 ]],

       [[1.    ],
        [0.918 ],
        [0.625 ],
        ...,
        [0.0546],
        [0.102 ],
        [0.181 ]],

       [[0.952 ],
        [0.914 ],
        [0.808 ],
        ...,
        [0.237 ],
        [0.237 ],
        [0.245 ]]], dtype=float32)

# Find the baseline (0.5 point)

In [16]:
from sklearn.dummy import DummyClassifier

dummy_clf = DummyClassifier(strategy="most_frequent")

dummy_clf.fit(train_x, train_y)

DummyClassifier(strategy='most_frequent')

In [17]:
from sklearn.metrics import accuracy_score
dummy_train_pred = dummy_clf.predict(train_x)

baseline_train_acc = accuracy_score(train_y, dummy_train_pred)

print('Baseline Train Accuracy: {}' .format(baseline_train_acc))

Baseline Train Accuracy: 0.5847092605886576


In [18]:
dummy_test_pred = dummy_clf.predict(test_x)

baseline_test_acc = accuracy_score(test_y, dummy_test_pred)

print('Baseline Test Accuracy: {}' .format(baseline_test_acc))

Baseline Test Accuracy: 0.5757956448911222


# Build a cross-sectional (i.e., a regular) Neural Network model using Keras (with only one hidden layer) (2 points)

In [19]:
model = keras.models.Sequential([

    keras.layers.Flatten(input_shape=[80, 1]),
    keras.layers.Dense(80, activation='relu'),
    keras.layers.Dense(5, activation='softmax')      
])

In [20]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = tf.keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=30, validation_data=(test_x, test_y))

Epoch 1/30
175/175 [==============================] - 2s 4ms/step - loss: 0.6735 - accuracy: 0.7672 - val_loss: 1.4945 - val_accuracy: 0.5624
Epoch 2/30
175/175 [==============================] - 1s 3ms/step - loss: 0.4596 - accuracy: 0.8510 - val_loss: 0.9819 - val_accuracy: 0.5607
Epoch 3/30
175/175 [==============================] - 1s 3ms/step - loss: 0.4040 - accuracy: 0.8742 - val_loss: 0.3484 - val_accuracy: 0.8987
Epoch 4/30
175/175 [==============================] - 1s 3ms/step - loss: 0.3625 - accuracy: 0.8887 - val_loss: 0.5071 - val_accuracy: 0.8291
Epoch 5/30
175/175 [==============================] - 0s 3ms/step - loss: 0.3422 - accuracy: 0.8950 - val_loss: 0.3466 - val_accuracy: 0.8915
Epoch 6/30
175/175 [==============================] - 1s 3ms/step - loss: 0.3163 - accuracy: 0.9047 - val_loss: 0.3075 - val_accuracy: 0.9121
Epoch 7/30
175/175 [==============================] - 1s 3ms/step - loss: 0.2936 - accuracy: 0.9106 - val_loss: 0.2627 - val_accuracy: 0.9276
Epoch 

In [21]:
scores = model.evaluate(test_x, test_y, verbose=0)
print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

# Huge improvement over the baseline

loss: 0.25
accuracy: 93.34%


# Build a deep cross-sectional (i.e., regular) Neural Network model using Keras (with two or more hidden layers) (2 points)

In [22]:
model = keras.models.Sequential([

    keras.layers.Flatten(input_shape=[80, 1]),
    keras.layers.Dense(60, activation='relu'),
    keras.layers.Dense(40, activation='relu'),
    keras.layers.Dense(20, activation='relu'),
    keras.layers.Dense(5, activation='softmax')      
])

In [23]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = tf.keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=30, validation_data=(test_x, test_y))

Epoch 1/30
175/175 [==============================] - 2s 4ms/step - loss: 0.7185 - accuracy: 0.7538 - val_loss: 1.1752 - val_accuracy: 0.7098
Epoch 2/30
175/175 [==============================] - 1s 3ms/step - loss: 0.4778 - accuracy: 0.8388 - val_loss: 0.8977 - val_accuracy: 0.6193
Epoch 3/30
175/175 [==============================] - 1s 3ms/step - loss: 0.4171 - accuracy: 0.8616 - val_loss: 0.3452 - val_accuracy: 0.8949
Epoch 4/30
175/175 [==============================] - 1s 3ms/step - loss: 0.3571 - accuracy: 0.8864 - val_loss: 1.0299 - val_accuracy: 0.6265
Epoch 5/30
175/175 [==============================] - 1s 3ms/step - loss: 0.3265 - accuracy: 0.8982 - val_loss: 0.4020 - val_accuracy: 0.8551
Epoch 6/30
175/175 [==============================] - 1s 3ms/step - loss: 0.3047 - accuracy: 0.9042 - val_loss: 0.4338 - val_accuracy: 0.8346
Epoch 7/30
175/175 [==============================] - 1s 3ms/step - loss: 0.2833 - accuracy: 0.9101 - val_loss: 0.2512 - val_accuracy: 0.9276
Epoch 

In [24]:
scores = model.evaluate(test_x, test_y, verbose=0)
print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 0.26
accuracy: 94.22%


# Build a LSTM Model (with only one layer) (2 points)

In [25]:
from tensorflow.keras.callbacks import EarlyStopping
earlystop = EarlyStopping(monitor='val_loss', patience=5, verbose=1, mode='auto')
callback = [earlystop]

In [26]:
n_steps = 80
n_inputs = 1

model = keras.models.Sequential([
    
    keras.layers.LSTM(40, input_shape=[n_steps, n_inputs]),
    keras.layers.Dense(5, activation='softmax')
])

In [27]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=20, validation_data = (test_x, test_y), callbacks=callback)

Epoch 1/20
175/175 [==============================] - 11s 44ms/step - loss: 1.1256 - accuracy: 0.5788 - val_loss: 1.2098 - val_accuracy: 0.3710
Epoch 2/20
175/175 [==============================] - 7s 42ms/step - loss: 1.0650 - accuracy: 0.5849 - val_loss: 1.0497 - val_accuracy: 0.5683
Epoch 3/20
175/175 [==============================] - 7s 42ms/step - loss: 0.9503 - accuracy: 0.6482 - val_loss: 0.8829 - val_accuracy: 0.6591
Epoch 4/20
175/175 [==============================] - 7s 42ms/step - loss: 0.7925 - accuracy: 0.7272 - val_loss: 1.1887 - val_accuracy: 0.4879
Epoch 5/20
175/175 [==============================] - 7s 41ms/step - loss: 0.7205 - accuracy: 0.7586 - val_loss: 0.7496 - val_accuracy: 0.6591
Epoch 6/20
175/175 [==============================] - 7s 40ms/step - loss: 0.6195 - accuracy: 0.8053 - val_loss: 0.5587 - val_accuracy: 0.8308
Epoch 7/20
175/175 [==============================] - 7s 41ms/step - loss: 0.5821 - accuracy: 0.8220 - val_loss: 0.5168 - val_accuracy: 0.845

In [28]:
scores = model.evaluate(test_x, test_y, verbose=0)
print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 0.77
accuracy: 75.67%


# Build a deep LSTM Model (with only two layers) (2 points)

In [29]:
n_steps = 80
n_inputs = 1

model = keras.models.Sequential([
    keras.layers.LSTM(60, return_sequences=True, input_shape=[n_steps, n_inputs]),
    keras.layers.LSTM(40, return_sequences=True),
    keras.layers.LSTM(20),
    keras.layers.Dense(5, activation='softmax')
])

In [30]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=20, validation_data = (test_x, test_y), callbacks=callback)

Epoch 1/20
175/175 [==============================] - 31s 137ms/step - loss: 1.1382 - accuracy: 0.5845 - val_loss: 1.1466 - val_accuracy: 0.5758
Epoch 2/20
175/175 [==============================] - 22s 125ms/step - loss: 1.1288 - accuracy: 0.5849 - val_loss: 1.1425 - val_accuracy: 0.5758
Epoch 3/20
175/175 [==============================] - 22s 125ms/step - loss: 1.1410 - accuracy: 0.5782 - val_loss: 1.1407 - val_accuracy: 0.5758
Epoch 4/20
175/175 [==============================] - 22s 127ms/step - loss: 1.1280 - accuracy: 0.5847 - val_loss: 1.1286 - val_accuracy: 0.5758
Epoch 5/20
175/175 [==============================] - 23s 131ms/step - loss: 1.1271 - accuracy: 0.5847 - val_loss: 1.1557 - val_accuracy: 0.5758
Epoch 6/20
175/175 [==============================] - 22s 126ms/step - loss: 1.1274 - accuracy: 0.5847 - val_loss: 1.1321 - val_accuracy: 0.5758
Epoch 7/20
175/175 [==============================] - 22s 126ms/step - loss: 1.1271 - accuracy: 0.5847 - val_loss: 1.1348 - val_ac

In [31]:
scores = model.evaluate(test_x, test_y, verbose=0)
print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 1.13
accuracy: 57.58%


# Build a GRU Model (with only one layer) (2 points)

In [32]:
n_steps = 80
n_inputs = 1

model = keras.models.Sequential([
    keras.layers.GRU(40, input_shape=[n_steps, n_inputs]),
    keras.layers.Dense(5, activation='softmax')
])

In [33]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=20, validation_data = (test_x, test_y), callbacks=callback)

Epoch 1/20
175/175 [==============================] - 11s 47ms/step - loss: 1.0776 - accuracy: 0.5967 - val_loss: 1.0730 - val_accuracy: 0.5611
Epoch 2/20
175/175 [==============================] - 7s 43ms/step - loss: 0.8327 - accuracy: 0.6945 - val_loss: 0.9338 - val_accuracy: 0.6181
Epoch 3/20
175/175 [==============================] - 8s 43ms/step - loss: 0.7843 - accuracy: 0.7190 - val_loss: 0.6138 - val_accuracy: 0.7848
Epoch 4/20
175/175 [==============================] - 8s 43ms/step - loss: 0.5426 - accuracy: 0.8352 - val_loss: 0.5527 - val_accuracy: 0.8070
Epoch 5/20
175/175 [==============================] - 7s 43ms/step - loss: 0.4292 - accuracy: 0.8672 - val_loss: 0.6684 - val_accuracy: 0.7554
Epoch 6/20
175/175 [==============================] - 8s 43ms/step - loss: 0.4044 - accuracy: 0.8760 - val_loss: 0.5930 - val_accuracy: 0.8116
Epoch 7/20
175/175 [==============================] - 7s 42ms/step - loss: 0.3464 - accuracy: 0.8957 - val_loss: 0.2978 - val_accuracy: 0.911

In [34]:
scores = model.evaluate(test_x, test_y, verbose=0)
print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 0.21
accuracy: 93.17%


# Build a deep GRU Model (with only two layers) (2 points)

In [35]:
n_steps = 80
n_inputs = 1

model = keras.models.Sequential([
    keras.layers.GRU(60, return_sequences=True, input_shape=[n_steps, n_inputs]),
    keras.layers.GRU(40, return_sequences=True),
    keras.layers.GRU(20),
    keras.layers.Dense(5, activation='softmax')
])

In [36]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=20, validation_data = (test_x, test_y), callbacks=callback)

Epoch 1/20
175/175 [==============================] - 35s 151ms/step - loss: 1.0284 - accuracy: 0.6179 - val_loss: 1.2323 - val_accuracy: 0.6449
Epoch 2/20
175/175 [==============================] - 24s 135ms/step - loss: 0.5847 - accuracy: 0.8080 - val_loss: 0.8678 - val_accuracy: 0.6834
Epoch 3/20
175/175 [==============================] - 23s 133ms/step - loss: 0.4053 - accuracy: 0.8726 - val_loss: 0.3177 - val_accuracy: 0.8982
Epoch 4/20
175/175 [==============================] - 23s 132ms/step - loss: 0.3294 - accuracy: 0.9008 - val_loss: 0.3159 - val_accuracy: 0.9012
Epoch 5/20
175/175 [==============================] - 23s 133ms/step - loss: 0.2975 - accuracy: 0.9106 - val_loss: 0.8215 - val_accuracy: 0.7592
Epoch 6/20
175/175 [==============================] - 23s 133ms/step - loss: 0.3206 - accuracy: 0.9013 - val_loss: 0.2744 - val_accuracy: 0.9221
Epoch 7/20
175/175 [==============================] - 23s 132ms/step - loss: 0.2848 - accuracy: 0.9151 - val_loss: 0.2419 - val_ac

In [37]:
scores = model.evaluate(test_x, test_y, verbose=0)
print("%s: %.2f" % (model.metrics_names[0], scores[0]))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

loss: 0.35
accuracy: 89.15%


# Discussion

## List the test values of each model you built (0.5 points)

## Which model performs the best and why? (0.5 points) 

## How does it compare to baseline? (0.5 points)